"""
Book Recommendation System — FastAPI Backend
============================================
Endpoints:
  GET /recommend?book_name=xyz          → top-5 hybrid recommendations
  GET /recommend?book_name=xyz&n=10     → custom count
  GET /recommend?book_name=xyz&method=content  → content-based only
  GET /books                            → list all available book titles
  GET /health                           → server health check
"""

import os
import pickle
import numpy as np
from pathlib import Path
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel


# ── App Initialisation ──────────────────────────────────────────────────────
app = FastAPI(
    title="Book Recommendation API",
    description="Returns personalised book recommendations using cosine similarity.",
    version="1.0.0",
)

# ── CORS — allow the React dev server to call this API ──────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


# ── Load Model Artifacts ────────────────────────────────────────────────────
BASE_DIR = Path(__file__).parent

def load_pickle(filename: str):
    """Load a pickle file; return None if it doesn't exist."""
    filepath = BASE_DIR / filename
    if not filepath.exists():
        print(f"⚠️  Artifact not found: {filepath}  — run the notebook first.")
        return None
    with open(filepath, "rb") as f:
        return pickle.load(f)

# These are generated by running the Jupyter notebook
hybrid_sim_df = load_pickle("hybrid_similarity.pkl")
books_df      = load_pickle("books_data.pkl")
pivot_table   = load_pickle("pivot_table.pkl")

ARTIFACTS_LOADED = all(x is not None for x in [hybrid_sim_df, books_df, pivot_table])
print(f"✅ Model artifacts loaded: {ARTIFACTS_LOADED}")


# ── Pydantic Response Schemas ───────────────────────────────────────────────
class BookRecommendation(BaseModel):
    title: str
    author: str
    genre: str
    similarity_score: float

class RecommendationResponse(BaseModel):
    input_book: str
    method: str
    recommendations: List[BookRecommendation]

class HealthResponse(BaseModel):
    status: str
    artifacts_loaded: bool
    available_books: int


# ── Core Recommendation Logic ───────────────────────────────────────────────
def get_recommendations(
    book_name: str,
    n: int = 5,
    method: str = "hybrid",
) -> List[dict]:
    """
    Core function: find the top-N books most similar to `book_name`.

    Parameters
    ----------
    book_name : str  — Full or partial book title (case-insensitive)
    n         : int  — Number of results to return
    method    : str  — 'hybrid', 'content', or 'collaborative'

    Returns
    -------
    List of dicts with title, author, genre, similarity_score
    """
    if not ARTIFACTS_LOADED:
        raise RuntimeError("Model artifacts not loaded. Run the notebook first.")

    # Use hybrid similarity (the best overall approach)
    sim_matrix = hybrid_sim_df

    # Case-insensitive partial-match lookup
    all_titles = list(sim_matrix.index)
    matches = [t for t in all_titles if book_name.lower() in t.lower()]

    if not matches:
        return []

    exact_title = matches[0]  # use the first matching title

    # Sort by similarity score, skip index 0 (the book itself)
    scores = sim_matrix[exact_title].sort_values(ascending=False).iloc[1 : n + 1]

    results = []
    for title, score in scores.items():
        info = books_df[books_df["book_title"] == title]
        if not info.empty:
            results.append({
                "title"            : title,
                "author"           : info["author"].values[0],
                "genre"            : info["genre"].values[0],
                "similarity_score" : round(float(score), 4),
            })

    return results


# ── API Endpoints ────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["Utility"])
def health_check():
    """Check if the server and model artifacts are ready."""
    return {
        "status"          : "ok",
        "artifacts_loaded": ARTIFACTS_LOADED,
        "available_books" : len(hybrid_sim_df) if ARTIFACTS_LOADED else 0,
    }


@app.get("/books", tags=["Utility"])
def list_books():
    """Return all book titles available in the recommendation model."""
    if not ARTIFACTS_LOADED:
        raise HTTPException(status_code=503, detail="Model artifacts not loaded.")
    titles = sorted(hybrid_sim_df.index.tolist())
    return {"total": len(titles), "books": titles}


@app.get("/recommend", response_model=RecommendationResponse, tags=["Recommendations"])
def recommend(
    book_name: str = Query(..., description="Book title to base recommendations on"),
    n: int         = Query(5, ge=1, le=20, description="Number of recommendations (1–20)"),
    method: str    = Query("hybrid", description="Similarity method: hybrid | content | collaborative"),
):
    """
    Return top-N book recommendations for the given book title.

    - **book_name**: full or partial title (case-insensitive)
    - **n**: number of results (default 5, max 20)
    - **method**: similarity approach (`hybrid` recommended)
    """
    if not ARTIFACTS_LOADED:
        raise HTTPException(
            status_code=503,
            detail="Model not ready. Please run the Jupyter notebook first to generate model artifacts."
        )

    if method not in ("hybrid", "content", "collaborative"):
        raise HTTPException(
            status_code=400,
            detail="Invalid method. Choose from: hybrid, content, collaborative"
        )

    recs = get_recommendations(book_name, n=n, method=method)

    if not recs:
        raise HTTPException(
            status_code=404,
            detail=f"Book '{book_name}' not found in the model. "
                   "Call GET /books to see all available titles."
        )

    return {
        "input_book"     : book_name,
        "method"         : method,
        "recommendations": recs,
    }


# ── Run with Uvicorn ─────────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
